spring.application.name=sanskriti-backend
server.port=${PORT:8080}

# Neon Postgres Database Configuration
# Appending "?sslmode=require" is mandatory for Neon
spring.datasource.url=jdbc:postgresql://ep-round-rain-am6g3k17-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YVA6v4sWCSUL
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Create tables in the public schema securely 
spring.jpa.properties.hibernate.default_schema=public

# HikariCP settings for Neon (handles aggressive connection closing)
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=300000
